### ISSUE TITLE
Contradicting version of files

### ISSUE THREAD

**Issue by mohanbabubb** [bitcraze/hardware#9]
i see the REV D on this file https://github.com/bitcraze/hardware/blob/master/src/products/crazyradio-pa/datasheet/crazyradio-pa-pcb-mechanics.png

but, the schematic pdf file shows, REV B, is it intentional ? or by mistake ?
https://github.com/bitcraze/hardware/blob/master/src/products/crazyradio-pa/electronics/crazyradio-pa_rev.b.pdf

**Comment by evoggy** [comment]
Thanks for the report. Yeah, it's an error. The image is the layout of the Crazyradio (not PA), which matches with the schematic for Crazyradio (latest revision is D). This needs a new screenshot for the mechanics (will be the same dimensions I think). I'm on it.

**Comment by mohanbabubb** [comment]
also, the file here show REV B diagram https://github.com/bitcraze/hardware/tree/master/src/products/crazyradio-pa/electronics , while store image shows REV C,, https://cdn.shopify.com/s/files/1/1028/5387/products/CrazyRadioBack_1024x1024.jpg?v=1467966118

**Comment by evoggy** [comment]
Thanks for the info, it should be fixed now. The reason for the difference in revision between the schematic and the layout is that there was only a layout change between B and C. So the schematic is rev B but the layout is rev C. We've changed how we make revisions of hardware now, so with today's system the new revision would be B1 instead.
